---
resources:
- name: resource-sample
  type: git
  source:
    uri: https://github.com/ehaydenr/concourse-sample.git

jobs:
- name: get-time
  public: true
  plan:
  - get: resource-sample
  - task: get-time
    file: resource-sample/get-time/get-time.yml
