---
resources:
- name: resource-sample
  type: git
  source:
    uri: https://github.com/ehaydenr/concourse-sample.git

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource-sample
  - task: hello-world
    file: resource-sample/get-time/get-time.yml
